### ISSUE TITLE
Error enumerating and uploading files

### ISSUE THREAD

**Issue by camjcorley** [cedrozor/myrtille#217]
Hello,

I'm unsure if this is related to issue #215 and decided to create a separate incident. 

Setup:
Domain Controller with Myrtille on Windows Server 2016.
Computer named "qeevtsd1" that is joined to the domain and on Windows Server 2016.
I am connecting to qeevtsd1 remotely via the Myrtille web portal on the DC using a domain user.
The domain user's account has folder redirection enabled via Group Policy and is configured as described in the Myrtille Documentation.
Everything appears to be working correctly except for files.

GetUserDocumentsFolderFiles Error:
```
2020-03-23 14:25:26,191 [9] ERROR System.Diagnostics redirection [(null)] - Failed to retrieve the user documents (System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Logon failure: the user has not been granted the requested logon type at this computer (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ComponentModel.Win32Exception: Logon failure: the user has not been granted the requested logon type at this computer
   at Myrtille.Helpers.AccountHelper.GetUserDocumentsFolder(String userDomain, String userName, String userPassword)
   at Myrtille.Services.FileStorage.GetUserDocumentsFolderFiles(Guid remoteSessionId, String userDomain, String userName, String userPassword)
   at SyncInvokeGetUserDocumentsFolderFiles(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean is...).)
```

UploadFileToUserDocumentsFolder Error:
```
2020-03-23 14:25:26,213 [9] ERROR System.Diagnostics redirection [(null)] - Failed to upload file Domains.xlsx to user one.qeev documents folder, remote session 7008bba3-ac66-4bd7-8362-c9fbcd13c97a (System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: Logon failure: the user has not been granted the requested logon type at this computer (Fault Detail is equal to An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.ComponentModel.Win32Exception: Logon failure: the user has not been granted the requested logon type at this computer
   at Myrtille.Helpers.AccountHelper.GetUserDocumentsFolder(String userDomain, String userName, String userPassword)
   at Myrtille.Services.FileStorage.UploadFileToUserDocumentsFolder(UploadRequest uploadRequest)
   at SyncInvokeUploadFileToUserDocumentsFolder(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)).)
```

I have modified the security settings for the folder and share to allow Full Control to Everyone to ensure that this is not related to the file permissions. Thanks!

**Comment by cedrozor** [comment]
Are you using the domain input field, in addition to username and password, into the login page ? indeed, you can login with user = "domain\username", but it should help for file upload if you login with domain = "domain" and user = "username"

**Comment by camjcorley** [comment]
I have tried both ways but the method I typically use (and other users will use in my environment) is connecting directly via URL query params. Example:

https://web.address/Myrtille/?__EVENTTARGET=&__EVENTARGUMENT=&server=qeevtsd1&domain=cjdevcam7.local&user=one.qeev&passwordHash=[passwordHash]&connect=Connect!

**Comment by cedrozor** [comment]
Hi, the problem is not related to the permissions on the network share but to the user account, which is not allowed to logon on the domain.

Is the DNS able to resolve the domain name from the myrtille machine? you can try a `nslookup cjdevcam7.local` for that purpose. Otherwise, you can also use the netbios name of the domain (`CJDEVCAM7`) instead of the FQDN.

**Comment by DrVaskee** [comment]
I think i get a related error. I'm trying the whole day to get the file upload working.
Inspecting the logs tells me that the GetUserDocumentsFolder function is failing:

`2020-03-24 15:10:56,259 [7] INFO  System.Diagnostics redirection [(null)] - Requesting authentication of user INTERNAL\vaske_yannick
2020-03-24 15:10:57,216 [7] INFO  System.Diagnostics redirection [(null)] - Requesting session host list
2020-03-24 15:10:58,817 [7] INFO  System.Diagnostics redirection [(null)] - Requesting session details
2020-03-24 15:11:00,008 [8] INFO  System.Diagnostics redirection [(null)] - Connecting remote session f3bbb4f9-f140-4511-939c-48f1c8d09207, type RDP, security AUTO, server (:port) 10.0.254.201, vm (none), domain INTERNAL, user vaske_yannick, program (none)
2020-03-24 15:11:22,464 [7] ERROR System.Diagnostics redirection [(null)] - Failed to retrieve file(s) from user vaske_yannick documents folder C:\Users\TEMP\Documents, remote session f3bbb4f9-f140-4511-939c-48f1c8d09207 (System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\TEMP\Documents" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.Directory.GetFiles(String path)
   bei Myrtille.Services.FileStorage.GetUserDocumentsFolderFiles(Guid remoteSessionId, String userDomain, String userName, String userPassword))`

The Folder Redirection ist working and the maschine where Myrtille is running has access to the folder. But somehow (i don't know if this is normal) when i try to upload a TEMP User is created and shortly after the Upload deleted again.

**Comment by camjcorley** [comment]
@cedrozor you're correct, I was able to enumerate and upload/download files when using a domain admin account to connect. I'll have to narrow down the access that the user accounts are missing. Thank you for your help!

@DrVaskee while the symptom/error is similar I believe that is a different issue. I'm marking this one as closed since my original inquiry is resolved. Obviously it's up to cedrozor but you may want to open a separate issue.

**Comment by cedrozor** [comment]
@DrVaskee I don't know about this "temp" profile, this is something managed by Windows.

Did you allowed multiple sessions per user ? (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services). By doing so, Windows should have a synchronization mechanism for roaming profiles (and avoid locking or creating temporary profiles).

@camjcorley is right, you should open another issue if the problem persists.

**Comment by camjcorley** [comment]
For future reference the problem was as follows:
The user accounts I'm using have logon access to the domain computer but not to the infrastructure server where Myrtille is installed.

To resolve this, I made the following change:
```
Myrtille.Services
|_ AccountHelper.cs
   |_ GetUserDocumentsFolder()
      |_ if (LogonUser(userName, string.IsNullOrEmpty(userDomain) ? Environment.MachineName : userDomain, userPassword, LOGON32_LOGON_NETWORK, LOGON32_PROVIDER_DEFAULT, ref token) != 0)
```
The change was to replace "LOGON32_LOGON_INTERACTIVE" with "LOGON32_LOGON_NETWORK".
This change seems to cause the account to authenticate against the domain instead of locally on the computer.

**Comment by cedrozor** [comment]
Thanks for your input. I remember having more luck with LOGON32_LOGON_INTERACTIVE  but it makes sense using a network authentication with a domain. I will make more tests and update the code accordingly.

**Comment by DrVaskee** [comment]
Also just fyi.
My Problem had nothing to do with the multiple sessions per user.
Somehow there was a Userprofile out of chinese letters. The Userprofile was not on the filesystem but in the registry, where the profilelist is stored.

The maschine was freshly installed before i added myrtille. After removing the entry from the registry it worked seamless.

**Comment by cedrozor** [comment]
Yes, I already noticed the chinese characters in profile names in some circumstances. I think hey are due to accentuated characters, or any other non ASCII character, in the user profile name. The Windows API methods work with wide strings (multibytes per character) and I must have forgot a conversion in some part of the managed C# code.

I will re-check that. Re-opening this issue for future reference.

Thanks for your inputs! :)

**Comment by cedrozor** [comment]
I made further investigations and found this:

- https://help.duo.com/s/article/1093?language=en_US
- https://social.technet.microsoft.com/Forums/lync/en-US/95ed510e-1a2e-47d5-a0e4-3a411857a46e/logon-failure-the-user-has-not-been-granted-the-requested-logon-type-at-this-computer-win-server?forum=winserver8gen

> Ensure that the users have been delegated the “Allow log on locally” rights for console logins, or have been delegated both the “Allow log on locally” and “Allow log on through Remote Desktop Services” rights in the computer’s local or domain-level security policy.

Basically, waiting for me to change the log on method from interactive to network when using a domain, as explained above, you can **allow the domain users to log on locally**, in addition to allow log on through remote desktop.

**Comment by cedrozor** [comment]
done in 2.9.0
