### ISSUE TITLE
Service Crashed

### ISSUE THREAD

**Issue by gtmsew** [cedrozor/myrtille#219]
I notice an error when I logged to the server that caused the Myrtille service to stop:

`Application: Microsoft.VsHub.Server.HttpHost.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController.ThrowLoggedException(System.String, System.String)
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController+<DownloadCompatibilityList>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController+<OnCompatibilityListMonitoringTimerElapsed>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

And one second earlier was this

`Application: Microsoft.VsHub.Server.HttpHost.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController.ThrowLoggedException(System.String, System.String)
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController+<DownloadCompatibilityList>d__17.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.ExtensionManager.HubServiceModule.ExtensionManagerHubService.ExtensionManagerServiceController+<OnCompatibilityListMonitoringTimerElapsed>d__18.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

This is first time this happened to me since mid January when I started using the new version

**Comment by cedrozor** [comment]
This process is spawned by Visual Studio; are you running Myrtille with it?

From https://stackoverflow.com/questions/31452435/how-do-i-disable-vshub-exe-in-the-system-tray/33153720#33153720

> the VS Hub is an out-of-proc services host that Visual Studio (and other VS shell-based products such as Blend) use in order to support multi-tool communication, better responsiveness within devenv (VS), and enable certain services to extend past the lifetime of the spawning process. The set of services currently hosted in the VS Hub includes many of the items called out in the other answers, such as roaming settings, processing of large swaths of ETL data that is rendered in the diagnostics tooling, some telemetry reporting, and extension auto update and notifications.

You should disable the VS diagnostic tool if you don't need it, it uses a lot of memory at the expense of other processes.

**Comment by cedrozor** [comment]
Hi, any news?

**Comment by gtmsew** [comment]
After last WU we are facing Myrtille crashing, but only on one of the host.
Here is the error

`Application: Myrtille.Services.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Diagnostics.Process.EnsureState(State)
   at System.Diagnostics.Process.get_HasExited()
   at Myrtille.Services.RemoteSessionProcess.ProcessExited(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)`

After 3min :

`Faulting application name: Myrtille.Services.exe, version: 2.8.0.0, time stamp: 0x5e2cf081
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3659, time stamp: 0x5e9140ed
Exception code: 0xe0434352
Fault offset: 0x0000000000034f38
Faulting process id: 0x6a04
Faulting application start time: 0x01d633858b570445
Faulting application path: C:\Program Files (x86)\Myrtille\bin\Myrtille.Services.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 10ee75e3-c625-41a5-a6f9-05e9ffe54cfe
Faulting package full name: 
Faulting package-relative application ID: `

And sometimes I see also this one:
`Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 5/7/2020 7:34:36 PM 
Event time (UTC): 5/7/2020 7:34:36 PM 
Event ID: 9fb28b9f00694a0ca07b72fe83bfef2c 
Event sequence: 31547 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/2/ROOT/webrdp-1-132333495161386789 
    Trust level: Full 
    Application Virtual Path: /webrdp 
    Application Path: C:\Program Files (x86)\Myrtille\ 
    Machine name: <MACHINENAME>
 
Process information: 
    Process ID: 40832 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\POOLNAME
 
Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at Myrtille.Web.RemoteSessionSocketHandler.OnClose()
   at Microsoft.Web.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSocketPipeline.<ProcessRequestImplAsync>d__9.MoveNext()

 
 
Request information: 
    Request URL:  
    Request path:  
    User host address:  
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: IIS APPPOOL\POOLNAME
 
Thread information: 
    Thread ID: 17 
    Thread account name: IIS APPPOOL\POOLNAME 
    Is impersonating: False 
    Stack trace:    at Myrtille.Web.RemoteSessionSocketHandler.OnClose()
   at Microsoft.Web.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSocketPipeline.<ProcessRequestImplAsync>d__9.MoveNext()
 
 
Custom event details: 
`
Service is crashing after the last Windows Updates at least once a day. I have configured a restart after failed so I can for now live with that, but any idea what can be the issue will be highly appreciated ;)

**Comment by cedrozor** [comment]
```
Application: Myrtille.Services.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Diagnostics.Process.EnsureState(State)
   at System.Diagnostics.Process.get_HasExited()
   at Myrtille.Services.RemoteSessionProcess.ProcessExited(System.Object, System.EventArgs)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)
```
I had some weird and random WCF deadlock issue between the myrtille services and gateway; following the advices of some people with the same problem on stackoverflow, I had the FreeRDP process exited callback into a separate thread and async (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L458).

It's unfortunate and surprising it can crash Myrtille.Services, because it's properly error handled (well, maybe not enough?). It happens on one host only and after Windows Updates?

The other log is an uncaught exception, nothing serious (I should just add an exception handling on the websocket close event).

**Comment by gtmsew** [comment]
Yes, only one host. It started just recently after we installed below updates:
![image](https://user-images.githubusercontent.com/51693068/83058214-51503a80-a058-11ea-930c-c94075e6399a.png)

**Comment by cedrozor** [comment]
Probably yes. You could try to reinstall the .Net Framework on this host.

**Comment by cedrozor** [comment]
Closing. please re-open if the issue still persists.
