### ISSUE TITLE
wfreerdp.exe and w3pw.exe are causing high CPU utilization

### ISSUE THREAD

**Issue by BarryLiu04** [cedrozor/myrtille#378]
wfreerdp.exe and w3pw.exe randomly cause high server CPU usage (over 95%).  Normally, the cpu utilization is around 5%-15%. Does anyone know the underlying cause?

**Comment by cedrozor** [comment]
Maybe some lack of available RAM? do you have something relevant in the Windows event logs (System or Application)?

**Comment by BarryLiu04** [comment]
> Maybe some lack of available RAM? do you have something relevant in the Windows event logs (System or Application)?

From what we see, the Memory Usage(%) never exceeded 80%.

Found this from Myrtille.Web.Log. Not sure if it's relevant.

2023-11-17 16:12:54,681 [59] ERROR System.Diagnostics redirection [(null)] - Websocket error, remote session 36d6d79a-2538-4353-a1a1-94447543e46f (System.Net.WebSockets.WebSocketException (0x80070026): Reached the end of the file
   at System.Web.WebSockets.WebSocketPipe.<>c__DisplayClass9_0.<ReadFragmentAsync>b__0(Int32 hrError, Int32 cbIO, Boolean fUtf8Encoded, Boolean fFinalFragment, Boolean fClose)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<DoWork>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.WebSockets.AspNetWebSocket.<>c__DisplayClass36_0.<<ReceiveAsyncImpl>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebSockets.WebSocketMessageReader.<ReadMessageAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Web.WebSockets.WebSocketHandler.<ProcessWebSocketRequestAsync>d__9.MoveNext())
