### ISSUE TITLE
Error in console/no display

### ISSUE THREAD

**Issue by Bluscrn99** [cedrozor/myrtille#397]
I've been trying to figure out how to use this software, and on connecting to my host i get a blank screen, and info says 0 img/s. I also noticed the dev mode console gives the following error:
contentScript.js:1 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at b (contentScript.js:1:1790)
    at contentScript.js:6:494
I don't know if these are related, but I would really like help with my display issues.
![image](https://github.com/user-attachments/assets/7798af15-2aa1-422d-8946-9124a8db969c)

**Comment by Bluscrn99** [comment]
nothing after almost a year

**Comment by SerkanOgutcuoglu** [comment]
a forgotten project

**Comment by Bluscrn99** [comment]
sad
