### ISSUE TITLE
Myrtille does not connect to a remote session

### ISSUE THREAD

**Issue by welsonplay** [cedrozor/myrtille#97]
My RDS environment with Myrtille was working properly, but after I rebooted to apply the Windows Server Update (KB4088787 - Security Patch) Myrtille stopped working.

I checked the Myrtille.Services.log file and it apparently does not show any errors:

```
2018-03-14 07:45:06,414 [4] INFO  System.Diagnostics redirection [(null)] - Service: Myrtille.Services.RemoteSessionProcess
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Endpoint: WSDualHttpBinding_IRemoteSessionProcess
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Address: http://localhost:8080/Myrtille/RemoteSessionProcess
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Binding: WSDualHttpBinding
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IRemoteSessionProcess
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - 
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Service: Myrtille.Services.FileStorage
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Endpoint: BasicHttpBinding_IFileStorage
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Address: http://localhost:8080/Myrtille/FileStorage
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Binding: BasicHttpBinding
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IFileStorage
2018-03-14 07:45:06,445 [4] INFO  System.Diagnostics redirection [(null)] - 
2018-03-14 07:45:34,862 [5] INFO  System.Diagnostics redirection [(null)] - Started remote session 1
2018-03-14 07:45:50,676 [5] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 1
2018-03-14 07:47:13,738 [4] INFO  System.Diagnostics redirection [(null)] - Service: Myrtille.Services.RemoteSessionProcess
2018-03-14 07:47:13,769 [4] INFO  System.Diagnostics redirection [(null)] - Endpoint: WSDualHttpBinding_IRemoteSessionProcess
2018-03-14 07:47:13,769 [4] INFO  System.Diagnostics redirection [(null)] - Address: http://localhost:8080/Myrtille/RemoteSessionProcess
2018-03-14 07:47:13,769 [4] INFO  System.Diagnostics redirection [(null)] - Binding: WSDualHttpBinding
2018-03-14 07:47:13,769 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IRemoteSessionProcess
2018-03-14 07:47:13,769 [4] INFO  System.Diagnostics redirection [(null)] - 
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - Service: Myrtille.Services.FileStorage
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - Endpoint: BasicHttpBinding_IFileStorage
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - Address: http://localhost:8080/Myrtille/FileStorage
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - Binding: BasicHttpBinding
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - Contract: Myrtille.Services.Contracts.IFileStorage
2018-03-14 07:47:13,785 [4] INFO  System.Diagnostics redirection [(null)] - 
2018-03-14 07:49:12,712 [8] INFO  System.Diagnostics redirection [(null)] - Started remote session 2
2018-03-14 07:49:28,663 [11] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 2
2018-03-14 07:51:13,182 [12] INFO  System.Diagnostics redirection [(null)] - Started remote session 3
2018-03-14 07:51:13,741 [6] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 3
2018-03-14 07:51:39,804 [11] INFO  System.Diagnostics redirection [(null)] - Started remote session 4
2018-03-14 07:51:40,330 [11] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 4
2018-03-14 07:52:27,948 [15] INFO  System.Diagnostics redirection [(null)] - Started remote session 5
2018-03-14 07:52:28,484 [6] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 5
2018-03-14 07:54:42,846 [16] INFO  System.Diagnostics redirection [(null)] - Started remote session 6
2018-03-14 07:54:58,293 [17] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 6
2018-03-14 07:56:19,509 [19] INFO  System.Diagnostics redirection [(null)] - Started remote session 7
2018-03-14 07:56:20,478 [20] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 7
2018-03-14 07:57:15,361 [22] INFO  System.Diagnostics redirection [(null)] - Started remote session 8
2018-03-14 07:57:16,321 [22] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 8
2018-03-14 07:59:56,680 [23] INFO  System.Diagnostics redirection [(null)] - Started remote session 9
2018-03-14 07:59:57,615 [24] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 9
2018-03-14 08:00:11,049 [20] INFO  System.Diagnostics redirection [(null)] - Started remote session 10
2018-03-14 08:00:11,191 [20] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 10
2018-03-14 08:01:27,406 [22] INFO  System.Diagnostics redirection [(null)] - Started remote session 11
2018-03-14 08:01:27,978 [21] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 11
2018-03-14 08:01:53,611 [24] INFO  System.Diagnostics redirection [(null)] - Started remote session 12
2018-03-14 08:01:54,132 [19] INFO  System.Diagnostics redirection [(null)] - Stopped remote session 12

```
The Myrtille.Web.log file is already displaying the following error:

```
2018-03-14 08:01:52,770 [61] ERROR System.Diagnostics redirection [(null)] - Failed to create remote session (System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Myrtille.Web.Default.ConnectButtonClick(Object sender, EventArgs e))
```

I am informing the credentials correctly, but I can no longer access through Myrtille, but using RDWeb and downloading the RDP file is working properly. Not whether the Windows update has generated the problem or not.

Another point that I checked, is that from time to time is happening the following error in the windows event log, but I do not know if there is a relation:

![image](https://user-images.githubusercontent.com/26077930/37400157-c34e4738-2762-11e8-9a39-58683e4b03c8.png)

Anyone have any idea what's going on?

**Comment by cedrozor** [comment]
The windows update may had changed something to the .net framework or config, or a COM object. From the warning event log, It looks like a permission issue with a COM object relative to the myrtille application pool.

In brief, this may prevent the myrtille web application to communicate with the myrtille WCF services.

I googled against CLSID D63B10C5-BB46-4990-A94F-E40B9D520160 and found that: https://shauncassells.wordpress.com/2015/09/28/windows-10-event-10016-fix-the-application-specific-permission-settings-do-not-grant-local-activation-permission-for-the-com-server-application-with-clsid-d63b10c5-bb46-4990-a94f-e40b9d520160-and-a/

If the error still occurs, you can try to switch the myrtille web application to the default "ASP.NET v4.0" (integrated pipeline) application pool, using the IIS management console.

**Comment by welsonplay** [comment]
I noticed that Myrtille works normally if I apply the Windows update or not, but I can not access any machines that have this update. If I try to access a machine that does not have this update I can access without any problem. Update KB4088787 is a security patch, which may have changed something by preventing me from connecting with Myrtille, but I can not identify what is precisely the problem.

**Comment by cedrozor** [comment]
It looks like a FreeRDP issue after KB4088787. I had a look to the update details (https://support.microsoft.com/en-us/help/4088787/windows-10-update-kb4088787) and checked the FreeRDP tracker but can't find anything.

Could you enable the FreeRDP logs (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L93 then restart the Myrtille.Services) and tell me if there is something useful?

**Comment by cedrozor** [comment]
Ok I digged a bit more and found the problem: https://github.com/FreeRDP/FreeRDP/issues/4483

It was fixed yesterday into the lastest FreeRDP commits: https://github.com/FreeRDP/FreeRDP/commit/e7ae3f6babc881d893411a5ada9156abe8525b2f

I'll resync the myrtille freeRDP fork asap. By the way, this could also fix a previous issue that made me code a workaround in the latest myrtille version! https://github.com/cedrozor/myrtille/issues/76  (I'll check that while resyncing).

In the while, you can disable NLA on the target machines (follow informations there: https://blog.royalapplications.com/2018/03/13/microsofts-march-13-2018-updates-and-royal-tsx/) to be able to connect them with myrtille.

**Comment by welsonplay** [comment]
Sorry for not giving you time to take the tests you requested.

Thank you very much for the quick response and identification of the problem. Is there any forecast to release a patched version?

**Comment by cedrozor** [comment]
I won't have much time this week-end but should be good next week

**Comment by mapl** [comment]
disabling NLA did not work for me. anyone had success doing this?

**Comment by welsonplay** [comment]
I did not get the tester because I did the rollback of the windows version. @mapl  have you disabled the NLA of all servers, including Gateway, Broker and Session Host?

**Comment by mapl** [comment]
I just have one Hyper-V VM windows server 2016 Server with IIS and myrtille and KB4088787 installed. NLA is disabled.
I tried to uninstalled the KB4088787 but then the VM stucks at the bootloader (hyper-v loader) after the required reboot. So I had to recover the VM.

**Comment by welsonplay** [comment]
With me the same problem happened in one of the servers, which I needed to repair. I still have a problem server, I will try to disable the NLA and I will try to access it and give you an answer.

**Comment by welsonplay** [comment]
Sorry for the delay @mapl . I did the test and could not access by disabling only the NLA. ive had to remove the update.

**Comment by mapl** [comment]
Thank you for festing. Unfortunalety, Removing the update is not possible right now as it leads to a non booting VM. I will wait for the next myrtille release.

**Comment by welsonplay** [comment]
I'll try some more adjustments and if I find the problem I'll inform

**Comment by cedrozor** [comment]
It should be fixed into myrtille 1.8.0 (beta), if you want to give it a try

**Comment by mapl** [comment]
it works again! thank you very much

**Comment by cedrozor** [comment]
Good :) thanks for feedback

**Comment by manjeet24feb** [comment]
Hi. 
I have Myrtille version 2.3.1 (stable), Windows 32 and 64 bits installed on Windows Server 2012 R2 datacenter(32gb ram, 8 core cpu). When i try to access the same machine on which Myrtille is installed through browser from remote machine it randomly gets connected. Most of the time it does not get connected. Very rarely it gets connected otherwise it just shows blank screen. In browser console the websocket request shows "pending" as status for request "Myrtille/SocketHandler.ashx?type=binary". 

However if myrtille in a browser in the same server(on which myrtille is installed. Quite stupid) and login as different user i am able acess and work. In browser console the websocket request shows "101" as status for request "Myrtille/SocketHandler.ashx?type=binary". But the issue occurs only if try to login through some remote machine. And it is random. Sometimes only it connects. Checked logs in myrtille.web.log. Found following errors. 
"System.Diagnostics redirection [(null)] - Failed to retrieve the active remote session (System.NullReferanceException: Object reference not set to an instance of an object at Myrtille.Web.PushUpdates.Page_Load(Object sender, EventArgs e))"

Restarting Myrtille Service does not help. Restarting the server does not help except the first time. Later the issue persists. Opening in Incognito, clearing browser cache etc. does not work.
